#!/bin/bash
.data

info1: .asciiz "Podaj liczbe a: "
info2: .asciiz "Podaj liczbe b: "
info3: .asciiz "Podaj liczbe c: "
info4: 	 .asciiz "Wynik: "

.text 
.global __start
__start:

	li $v0,4							# txt wczytanie liczby a
	la $a0,info1    
	syscall								 

	li $v0,5	
	syscall								# pobranie liczby a 
	move $t0,$v0						# przeniesienie do rejestru 

	li $v0,4							# txt wczytanie liczby b	
	la $a0,info2
	syscall

	li $v0,5							
	syscall								# pobranie liczby b 
	move $t1,$v0	                   			# przeniesienie do rejestru 

	li $v0,4							# txt wczytanie liczby c
	la $a0,info3    
	syscall								 

	li $v0,5	
	syscall								# pobranie liczby c 
	move $t2,$v0						# przeniesienie do rejestru 
	
	li $7, 7						#zapisanie w rejestrze cyfry 7
	li $2, 2						#zapisanie w rejestrze cyfry 2
		
	add $t3, $t0, $t1					# dodawanie (a+b)

	mult $7,$t3						# operacja mnozenia 7*(wynik dodawania a+b)
	mflo $s0	                       			# przeniesienie lo 32 bitow do $s0
	
	mult $2,$t1						# operacja mnozenia 2*b
	mflo $s1	                    			# przeniesienie lo 32 bitow do $s1
 
 	add $s0, $s0, $s1					#zapisanie w s0 wyniku dodawania (7*(a+b)) + (2*b)
 	add $s0, $s0, $t2					#zapisanie w s0 wyniku dodawania ((7*(a+b)) + (2*b)) + c
 	
 	li $v0,4						# wczytanie i wyświetlenie wyniku	
	la $a0,info4    
	syscall	 
 
	li $v0,1
	move $a0,$s0 						
	syscall

	li $v0,10						#zakończenie i wyjście
	syscall
